server {
        #Bloque que define un servidor virtual.
    listen 80;
        # Nginx escucha peticiones HTTP en el puerto 80.
    root /usr/share/nginx/html;
        # Directorio raíz donde están los archivos estáticos (build de React).
    index index.html;
        # Archivo que se sirve por defecto al acceder a la raíz.
    location / {
        # Regla para todas las rutas.
    try_files $uri $uri/ /index.html;
        # CLAVE para React Router: si el archivo no existe, sirve index.html para que React maneje la ruta en el cliente (SPA routing).
    }
    location /api/ {
        # Regla especial para las llamadas a la API del backend.
    proxy_pass http://backend:8080/;
        # Redirige las peticiones /api/* al servicio 'backend' en el puerto 8080 (nombre del servicio en docker-compose).
    proxy_set_header Host $host;
        # Pasa el host original al backend.
    proxy_set_header X-Real-IP $remote_addr;
        # Pasa la IP real del cliente al backend.
    }
}
